### ISSUE TITLE
Add CLI arguments to vira.py

### ISSUE THREAD

**Issue by mikeboiko** [n0v1c3/vira#1]
This would primarily be used to set server and auth info.
I could code this up using argparse.

**Comment by n0v1c3** [comment]
I am also working on this as well. Currently I use the vim script to pass the auth through and I thought of a pop-up to let you select your server, enter username, password. Then go into select project.

I have now started to use the python code in my day to day so I do expect it to become quite a powerful standalone from the CLI

**Comment by mikeboiko** [comment]
Ok nice. This is the format that I've used for a bunch of python scripts now and I think it's quite pythonic.

```
'''
Vira - do all the jira-ing in vim
'''

# The help file will show the module docstring with this class
parser = argparse.ArgumentParser(
    description=__doc__, formatter_class=argparse.ArgumentDefaultsHelpFormatter)

# Specify optional arg
parser.add_argument(
    '-u',
    '--user',
    action='store',
    default='travis',
    help='Jira user name'
)

# Main Code
# ...

# Run script if this file is executed directly
if __name__ == '__main__':
    args = parser.parse_args()
    main()

```

**Comment by n0v1c3** [comment]
Might as well put it in now. Do a pull request and I will merge it in.

**Comment by mikeboiko** [comment]
k will do

**Comment by n0v1c3** [comment]
I also have made some lame CLI menus for navigating and editing your issues. I will test your other uploads in my new VIM and then push them this evening.

**Comment by n0v1c3** [comment]
Although I am sure you are already using the function inside a CLI loop somewhere...

**Comment by mikeboiko** [comment]
#5 the merge looks good
