### ISSUE TITLE
Enable integration of CLI password managers

### ISSUE THREAD

**Issue by mikeboiko** [n0v1c3/vira#12]
I like the current prompting feature of g:vira_pass
However, I use the lastpass password manager CLI for all my password needs. It would be good if we had the option of running a script for the username/password instead of setting static strings.

For example, the vim config for me could like something like this:
```
let g:vira_user_script = "lpass show --username boiko.online"
let g:vira_pass_script = "lpass show --password boiko.online"
```

**Comment by n0v1c3** [comment]
I completely agree. I also use external password managers and it should be done this way.

**Comment by n0v1c3** [comment]
I think this will mostly be up to proper config but I like the way that you make it easy for the user to understand. I just wrote the vimscript to do the same thing for my password.

**Comment by n0v1c3** [comment]
This can also be done using the `system` function

**Comment by n0v1c3** [comment]
`let g:vira_pass = system("lpass show --password boiko.online")` should work

**Comment by n0v1c3** [comment]
I think that is the proper Vim solution.

**Comment by n0v1c3** [comment]
I have updated the readme.md file and it looks much better now. I completely removed the mention of putting your ASCII password into your files and you just need to know what you are doing if you want to do that.

**Comment by mikeboiko** [comment]
Nice, that looks good!

**Comment by n0v1c3** [comment]
I also added a timeout so it will not completely destroy your vim if the connection goes bad. The captcha is the only thing I can think about but you would need to complete that regardless.

I think I will switch to a new tab with tiny font and use `imagemagick` to turn the captcha into ASCII art but that will be version 2 of the official release I am sure.
