### ISSUE TITLE
Use pipenv for dependancy management

### ISSUE THREAD

**Issue by mikeboiko** [n0v1c3/vira#2]
Let's decide on which version of python we're using first of all. How about we stick with the latest stable release of 3.7?
After this, I can create a Pipfile to specify all required packages.

**Comment by n0v1c3** [comment]
The default is 2.7 in Vim. I have made sure that all of the current  libraries work with a min version of that.

**Comment by mikeboiko** [comment]
Well I'm pretty sure you can use python3. You can check your vim install:

```
echo has('python')
echo has('python3')
```

I would urge against using python 2 as it is quite outdated now and many libraries are moving away from it. That being said it will get the job done in the meantime but would not be a good path for the future.

**Comment by n0v1c3** [comment]
You can use python 3 however, I do like keeping it able to run in 2 if possible then there is no future explanations required to future users. And it will not matter what version of Python they are running it should just work. (Provided they know how to add the required libs to the proper version of python)
`python3 -m pip ...`
`python2 -m pip ...`

**Comment by n0v1c3** [comment]
If anything comes out of Python3 that we cannot live without then I will happily change a readme explaining the process.

**Comment by mikeboiko** [comment]
Sounds good, let's go with python 2.7 then. That being said, I would still suggest using pipenv. This way you can sit down on any machine, download the repo and then run the following:

```
pipenv install
pipenv run python jira.vim
```

This will ensure the exact versions of each library are used and will produce consistent results.

**Comment by n0v1c3** [comment]
I need to write this comment for my IT guy.

**Comment by mikeboiko** [comment]
#

**Comment by mikeboiko** [comment]
#4 did the trick

**Comment by n0v1c3** [comment]
I will run a test on the merge that I did at home and then close this issue.

**Comment by n0v1c3** [comment]
If you tested it good enough for me keep it closed.

**Comment by mikeboiko** [comment]
Yea I tested it. It should be good to go.

**Comment by mikeboiko** [comment]
I found one minor annoying thing about python2 thus far. You can't do f-strings...

```
var = 'world'
print('hello ' + var) # python2
print(f'hello {var}') # python3.6+
```

Not really a deal-breaker :P
