### ISSUE TITLE
Getting my password wrong locks my vim for 30s

### ISSUE THREAD

**Issue by mikeboiko** [n0v1c3/vira#20]
It would be good to have a shorter timeout period

![image](https://user-images.githubusercontent.com/24229496/52247740-46442a80-28a8-11e9-8ca7-30c586cf5ea1.png)

**Comment by n0v1c3** [comment]
I did reduce the timeout. Believe me it used to be a 8 minute crash when I was first setting it up 😓. What it needs now is a simple try catch and the red lines can go away and it should be closer to a 15 second Vim Crash.

echo Connecting to <server>...
3 attempts with 5 second time out
echo Connected/Failed: ERROR <er #>

I will probably reduce the 3 attempts to 1 and let the user try again on their own. This also help reduce the chance of locking yourself out.

**Comment by n0v1c3** [comment]
The reduction in the number of tries will be the major reduction in time Vim locked for. I should also be able to run this as a parallel process and simply use the out and statusline to show what is going on.

**Comment by mikeboiko** [comment]
I like the idea of logging in asynchronously!

**Comment by n0v1c3** [comment]
I have moved this along with some other login issues to "Highest" priority and should be patched soon.

**Comment by mikeboiko** [comment]
Sweet, thanks!

**Comment by n0v1c3** [comment]
Other than a coffee I should not miss this evening and a job in my way looking at the list I should be able to fix most of it by tonight or tomorrow night.

**Comment by mikeboiko** [comment]
Right on!

**Comment by n0v1c3** [comment]
This issue should be fixed on the master branch
