### ISSUE TITLE
Use linter/auto-formatter for python files

### ISSUE THREAD

**Issue by mikeboiko** [n0v1c3/vira#3]
I propose to use flake8 as a linter
I propose using yapf as an auto-formatter

I have good settings configured for these 2 and can add them to the repository.

flake8/yapf should ideally be used within vim using the ALE (asynchronous linting package)

**Comment by mikeboiko** [comment]
We should also tie them to pre-commit git hooks.

**Comment by n0v1c3** [comment]
For sure regarding the the pre-commit hooks. I wrote most of this at work in Notepad++ so I am sure there is lots of mistakes plus my server at home has not been fully configured to work properly (missing some vim installs) so I am sure it is not looking at my python code correctly (I dont even remember any errors logs showing up when I opened it at home).

**Comment by n0v1c3** [comment]
We can set this up and I will fix my new server.

**Comment by mikeboiko** [comment]
Sounds good. Well why don't I do a pull request with my flake8/yapf config file for the time being and you can tweak as you like?

**Comment by n0v1c3** [comment]
Sounds good to me.
