### ISSUE TITLE
Cannot filter users when using an atlassian jira connection

### ISSUE THREAD

**Issue by n0v1c3** [n0v1c3/vira#35]
As a user I currently cannot use the `ViraFilterAssignees` function.

As a developer I have also removed the read data from the `ViraComment` command to prevent the same issue regarding VIRA-164.

**Comment by n0v1c3** [comment]
We will most likely need to use `self` and `displayName` again.

```
"reporter": {
            "accountId": "5a5d22db76a09c4111f48b15",
            "accountType": "atlassian",
            "active": true,
            "avatarUrls": {
                "16x16": "https://secure.gravatar.com/avatar/c51529af673ffceb0a9b7f1730bdbae8?d=https%3A%2F%2Favatar-management--avatars.us-west-2.prod.public.atl-paas.net%2Finitials%2FMB-5.png",
                "24x24": "https://secure.gravatar.com/avatar/c51529af673ffceb0a9b7f1730bdbae8?d=https%3A%2F%2Favatar-management--avatars.us-west-2.prod.public.atl-paas.net%2Finitials%2FMB-5.png",
                "32x32": "https://secure.gravatar.com/avatar/c51529af673ffceb0a9b7f1730bdbae8?d=https%3A%2F%2Favatar-management--avatars.us-west-2.prod.public.atl-paas.net%2Finitials%2FMB-5.png",
                "48x48": "https://secure.gravatar.com/avatar/c51529af673ffceb0a9b7f1730bdbae8?d=https%3A%2F%2Favatar-management--avatars.us-west-2.prod.public.atl-paas.net%2Finitials%2FMB-5.png"
            },
            "displayName": "Mike Boiko",
            "self": "https://n0v1c3.atlassian.net/rest/api/3/user?accountId=5a5d22db76a09c4111f48b15",
            "timeZone": "America/Denver"
        },
```

**Comment by mikeboiko** [comment]
Along with issues listed, we'll have to make sure that the new issue assignee input field is still working properly.

**Comment by n0v1c3** [comment]
Set and Get will need to be fixed they are both based on the same issue.

**Comment by n0v1c3** [comment]
This issue should now be working on both private servers and the public atlassian.net along with api2 and api3.

**Comment by n0v1c3** [comment]
Reopened. Duplicate Unassigned and Comment Usage

**Comment by n0v1c3** [comment]
Got the repeating Unassigned users removed along with an alphabetized list other than Unassigned at the bottom.

VIRA-164

**Comment by n0v1c3** [comment]
Filters appear to work. But I did catch that Atlassian pull has repeating statuses.

**Comment by n0v1c3** [comment]
Repeating data in Statuses is cleaned up.

**Comment by n0v1c3** [comment]
I think I will call this closed and create another public issue if required.
