### ISSUE TITLE
Feature request - functions or commands for setting default filters

### ISSUE THREAD

**Issue by jestinjht** [n0v1c3/vira#38]
This tool would be a lot more useful if I could set up default filters, rather than have to manually select them each time I enter my editor.  For example, my company hosts about 100 projects in a shared Jira server, and only one or two of those are all I'll ever care about.  Right now, I have to select these each time I open my editor, but it would be nice to write this into my .vimrc file instead.

**Comment by n0v1c3** [comment]
If you have a look at the Jira Projects section of the README we have started this and always looking for ways to make it better.

This currently uses the name of the directory your project will be in and we are looking at was to expand it. We do have some ideas building for saving and loading your favorite filters so you are able to jump between them and save them along the way.

We do also have the filters that can be implemented on the fly. These filters do include a multiple select with the `s`.

**Comment by mikeboiko** [comment]
Yes we agree and are working on a being able to change servers/filters with commands, rather than exclusively with the interactive menu.

**Comment by n0v1c3** [comment]
@jestinjht I need to do some clean-up on my current highlighting updates coming and that will make holding the current filters easier. Saving/Loading those will be after that. Also a reminder for myself there are the Basic filters we have and we also need to create access to full JQL.

**Comment by n0v1c3** [comment]
@jestinjht I should have mentioned that `__default__` can be used within the `vira_projects.json` file. This will allow you to have a default mapping for all directories on initial load.

@mikeboiko has also added the function `ViraLoadProject` that can be configured in your vimrc to quick switch between filters and servers in the `vira_projects` file.

**Comment by n0v1c3** [comment]
@jestinjht apparently @mikeboiko added `ViraFilterEdit` at least a little while ago sneaking by me. It helps to see all filter fields and edit them from a single location. I think this will cover this issue for the most part.

We have also talked about adding a raw JQL into that list that can be OR'd in some way with the rest of your filtering. Calling it closed but we will be working on filters forever most likely.
