### ISSUE TITLE
Default filters assigned in vira_projects are not applied

### ISSUE THREAD

**Issue by uberbrodt** [n0v1c3/vira#44]
I've configured `~/.config/vira/vira_projects.json` like so:
```
{
    "/path/to/repo": {
        "server": "https://myproject.atlassian.net",
        "filter": {
            "project": "CB",
            "assignee": "Chris Brodt",
            "component": "Development"
        }
    }
}
```
but when I run `:ViraIssues` or `:ViraReport` I get an unfiltered list of issues. Applying the filters with the ex commands in does work.

**Comment by n0v1c3** [comment]
I will start a double check on my filters. 

Is the main missing part of the filter the assignee? It looks like you are using an atlassian service and I have an issue so you can use your name like you have it and not the crazy accountID

**Comment by n0v1c3** [comment]
You should see your account ID in the filter assignee/reporter menus.

**Comment by n0v1c3** [comment]
You should be able to use your name and not a rediculuse account ID.

I assume you are using a full path and not just the dir name? is `/path/to/dir` vs `dir` apparently we do not take a full path and makes me laugh a bit. Should not be the Linux user in me.

**Comment by uberbrodt** [comment]
So "component" wasn't working for me either, so I assumed it wasn't working
entirely. I'll update the account id, thanks for the tip.

So what's the standard on the project name? Should it just be the directory
of the repo, no the path?

For example, if my repo is at /home/cbrodt/some_project, is the correct
name in the vira_projects.json `some_project`?

**Comment by n0v1c3** [comment]
NOT the path right now. :(

I quickly added that one to the list as I care about my paths normally.

ACCOUNTID should not be an issue I did do a double check on my Atlassian and not my Private and it should not care that you used your name.

**Comment by n0v1c3** [comment]
Also, without the vira_projects file at all I assume you are not having issues applying the filters on the go?

**Comment by uberbrodt** [comment]
Yep, the `:ViraFilter*` methods work perfectly.

So I updated the project name to match the name of the project
directory, but still seems like the `filter` defined in the projects
json are not being applied.

**Comment by n0v1c3** [comment]
I restarted on very simple this worked for me. It is important to not that you currently must be in that directory I haven't double checked but I am guessing cd in vim will be a fail for me. ie I `cd $n0v1c3/vira; vim`

```
 {
      "vira": {
        "server": "https://n0v1c3.atlassian.net",
        "filter": {
          "project": "VIRA"
        }
      }
 }
```

If it was the directory we have talked about this a bit and do not currently want to change your filters as directories are changed inside vim. This is only to load it preemptively. Future is save and load filters as well.

**Comment by n0v1c3** [comment]
I might also suggest to use `"__default__"` as this will apply everywhere and you can make more specific ones for the folder you are in at the moment.

**Comment by n0v1c3** [comment]
@uberbrodt I have created issue VIRA-225 and moved it high in priorities. Our current check for `git` will auto send you to `__default__` if you are not in a `git` repo.

**Comment by n0v1c3** [comment]
I have checked the first step of the solution in on the `VIRA-220` (different issue) branch it should cover the basics from my notes but I need some cleanup to get `dev` ready for a `master` push.

**Comment by n0v1c3** [comment]
@uberbrodt I have made the push to `master` VIRA 0.4.0 please let me know if I have made this work for non-git dirs for yourself.

It should accept full paths, just dir name, git root dir full/dir name. Git is the first to be looked at otherwise you will need to be in the same folder on load of vira.

@mikeboiko has also added a nice feature `ViraLoadServer` that can be used for quick filter switches within vim and stop worrying about the dir you are in.

Here is an example to switch my "branch" to vira at any time. This will then take the vira settings from the vira_project file and apply them. It will also help to quick switch if you are working on multiple jira servers.

`nnoremap <silent> <leader>vbv :ViraLoadProject vira<cr>`

**Comment by n0v1c3** [comment]
Calling this one closed. Let me know if we missed anything.
