### ISSUE TITLE
make open ViraReport configurable

### ISSUE THREAD

**Issue by chinwobble** [n0v1c3/vira#48]
I have very limited screen space.

When I open a VIRA report I would ideally like to open in full width rather than split.

I see the in the autoload file you hard code it to open in botright.

Would you be open to making that customisable?

**Comment by n0v1c3** [comment]
We do have a variable hidden in our `README` that will control the width of the report `g:vira_report_width`

Add the following to your `.vimrc` and you can play with the width. I can make new issues for default left, right, up and down as well if needed. I did have a line at some point in my vim for left and right.

```
let g:vira_report_width = 20
```

**Comment by n0v1c3** [comment]
We do also have an issue for this to become available on tabs. We can move that up in priority once I am done with `VIRA-69`

**Comment by n0v1c3** [comment]
@chinwobble just for you once you approve VIRA-274 I will get this one done next for you just out of the value of the async for some repayment.

I don't believe it should be too hard but vim script can always correct me there. This also will be a relatively quick fix as the async will need lots of integration all over our code now as well.

I can worry about the output of the version menu while I work on this as long as you are getting your list of versions without ridiculous lag. This is the filter filter I talk about so if you filter a project it only shows you versions from that project, I have broken that recently.

**Comment by n0v1c3** [comment]
Also, keep pushing as many ideas, issues and improvements towards me as possible. VIRA-69 was a big attack on Epics then we are on a cleanup round for version 0.5.0 or 1.0.0 however, async got in in time that we can build a good list to make it great for version 1.0.0.

**Comment by chinwobble** [comment]
I implemented this workaround in my vimrc
```viml
augroup vira_customizations
  autocmd!
  autocmd WinEnter,BufEnter vira_report silent! wincmd J | wincmd _
augroup END
```

**Comment by n0v1c3** [comment]
I am sure that line of code will become attached to a `g:` variable, smart enough for a must be used if screen didn't reach minimum size,  and a choice between the two on the fly. All built in, I should be able to test it quickly. Code it might take a moment or two.

**Comment by n0v1c3** [comment]
@chinwobble if you have any other her ideas such as the left, right up down just on my mind or the list above let me know I have made a real issue for this and may as well start tracking the list of "making it look good for me"

**Comment by n0v1c3** [comment]
I will be pushing this following line onto the active fix branch.

```
autocmd BufEnter vira_report silent! wincmd T
```

This will go right into tab mode if you set `g:vira_report_position = T` I believe that should be good now.

**Comment by n0v1c3** [comment]
I may make the previous existing variable  g:vira_report_width = -1 for T. I still need to add in the auto calculator for if less than 50%ish auto tab.

Let me know what you think about that. For know the previous one is working on our test branch.

**Comment by n0v1c3** [comment]
@chinwobble I am sure there will be one more renaming of the variable but the reuses the existing one I had. Numbers can also be used with `0` for Tabs. I think that should call this one done once you pass it.
```
let g:vira_report_width = 'T'
let g:vira_report_width = 'H'
let g:vira_report_width = 'L
```

**Comment by n0v1c3** [comment]
I think I can easily close this one as well and we can keep opening new ones.

I did just jupdate the default back to the `L` mapping as this is where it has been for quite a while and really bugged me once all I wanted to do was dealt everything so MY code works for ME. 🧑‍💻

**Comment by n0v1c3** [comment]
I do very much understand it is much more complicated than that now especially when I need to review my own README now for how it works...

@chinwobble; @mikeboiko and myself will definitely appreciate a new list of was to make a reports better for you is any way. From style to `try`, perfect timing and just our great form of development sense of humor developing along the way.

**Comment by chinwobble** [comment]
I'm using dev branch and I have this in my `vimrc`
```viml
let g:vira_report_position = 'T'
let g:vira_report_width = 0
```

However when I run `:ViraReport` it still shows up on the right as a split.

**Comment by n0v1c3** [comment]
You should only need:
`let g:vira_report_width = 'T'`
OR
`let g:vira_report_width = '0'`

I dropped position during that branch sorry :(

**Comment by n0v1c3** [comment]
Apparently I will need to max an issue for a non character `0`

**Comment by chinwobble** [comment]
thanks ` let g:vira_report_width = 'T'` works for me now.
