### ISSUE TITLE
VIRA-272: select site in :ViraIssues, then nothing happens??

### ISSUE THREAD

**Issue by wym2010** [n0v1c3/vira#62]
![image](https://user-images.githubusercontent.com/22862848/111570680-48477a00-87e0-11eb-94f5-f34b87582728.png)
![image](https://user-images.githubusercontent.com/22862848/111570713-572e2c80-87e0-11eb-87c2-54a58298a6d1.png)

**Comment by wym2010** [comment]
I use latest version of Vira, on centos7, Jira version is v8.13.1.
also I can not login with correct password with "#" character included in.

**Comment by n0v1c3** [comment]
Hello @wym2010 thanks for letting me know that something is not working and not giving you much information as to why.
- [ ] vira_servers file?A
- [ ] key password or personal password?
- [ ] vim or nvim?
- [ ] manually opening server login window? Or, opening issues and forced to login then allowed to open issues?
- [ ] Python3? Looks like that is not an issue
- [ ] Linux, Mac, ...Windows?
That should be a fun round to start with.

**Comment by n0v1c3** [comment]
What terminal are you using while we are at it as well?

**Comment by n0v1c3** [comment]
@wym2010 try a test on VIRA 0.4.9 update for the `master` branch and that would have been some issues that were not on my list before.

I will also check if you are logging into a server with many and/or larger projects/versions. The VIRA 0.4.8 has a temp patch that should work around heavy lag from that now.

**Comment by n0v1c3** [comment]
@wym2010 you still out there? I am going to close this one if it is working for you otherwise, I am still happy to look into it with you to get it working for you and as always easier for the next users.

**Comment by n0v1c3** [comment]
@wym2010 I am closing the issue but feel free to open it again any time if you want to got get it working for you.

**Comment by n0v1c3** [comment]
@wym2010 I know I have closed this one a little while ago but I believe it may have been related to the single server only issue that I needed to do a patch for.

You should be able to give it a try now. If you only have one server configured it should auto login for any menu calls and ignore that window for servers. That window will now only appear for no servers and multiple servers when not ran from a folder configured in `vira_projects`.
