### ISSUE TITLE
vim: create a menu

### ISSUE THREAD

**Issue by n0v1c3** [n0v1c3/vira#7]
I have looked at a lot of the plugins but I am pretty sure we will need a full custom menu created from a temp buffer to pull of what I am dreaming.

Unite is pretty easy plugin to work with but I really want to "re-create" what is in the browser. I will break it down further what I think can be done but I have a feeling it is going to be a lot of Vim script.

I can almost create a "useful" popdown menu while in normal or insert mode using the "complete" and outdated "popup" vim commands and they seem pretty good for commenting and time tracking (select an issue to comment/start tracking)

**Comment by n0v1c3** [comment]
I would like to keep the swimlanes in mind while creating a full buffer menu. We should be able to; get required info to display, create a layout with the current number of columns (always split across the top or bottom of all vim buffers), send layout to a read-only buffer of vira type, open and position the buffer in vim), go to the first/current issue, write custom navigation and highlighting into an autoload vim script for the plugins (j down issue in current swimlane, k right swimlane, ctrl k up status of issue...).

I think that covers the dream then expand on that.

**Comment by n0v1c3** [comment]
Oh and enter takes you into the issue for a detailed view and another key to select that issue as your active issue.

**Comment by mikeboiko** [comment]
Sounds like you have given this a lot of thought. I'm good with these things. The only curve-ball I'd throw at this whole idea is considering to write the program as a standalone TUI (terminal user interface) rather than coding it in vim-script. Similar to TUIs people make with ncurses. Although if we were to go down this route I would suggest using the python library prompt_toolkit or something along those lines. Then you could just run the TUI app from vim with :terminal python tui_app.py

The main advantage to this method would be that you could use this as a standalone script from the terminal - no need to tie yourself to vim. 
The disadvantage would be it could take some extra effort to integrate the application within VIM.

So yea I'm good either way really - just thought I'd throw this idea out there.

**Comment by n0v1c3** [comment]
I though of using something like Terminal User Interface but I haven't played enough using these inside VIM but pumping the info back and forth should not be too difficult. Although, if it stays in a VIM buffer we should be able to do anything with the display.

**Comment by mikeboiko** [comment]
Yea we could give it a shot using pure vim-script and if anything seems like it's more trouble that it's worth, switch to a more powerful language for those items.

**Comment by n0v1c3** [comment]
I have a feeling Python will be doing a lot of the heavy lifting in the preparing the layout and then we should just need to but functions/bindings into our custom buffer type for navigation and other hotkeys.

python gets vim info > prepares output > vim loads into buffer > custom keys and highlighting in vimscript

**Comment by mikeboiko** [comment]
I like the idea of using python to do the grunt work

**Comment by n0v1c3** [comment]
Looking at some semi-abandoned code [Unite](https://github.com/Shougo/unite.vim) looks to have a lot of code that should be useful to creating a quick menu in a buffer that can later be customized to look how we want.

**Comment by mikeboiko** [comment]
I like the look of that a lot! It's great that it integrates with ctrl-p also.

**Comment by n0v1c3** [comment]
Very similar to what you had shown me in that email and easy enough to start with as just a required plugin that can be recreated if I choose to expand this.

**Comment by mikeboiko** [comment]
Yea that's right - it should be easy enough to use Unite with the vira python wrapper to create most of the required functionality.

**Comment by n0v1c3** [comment]
That is what I was seeing. I think you or I and both of us can have this functional before the weekend. I am going to start implementing and testing tonight.

Let me know any thoughts/requirements you have along the way.

**Comment by mikeboiko** [comment]
Ok thanks, that sounds great. I'm mostly working 12h days this week and next week and then I'm off on a snowboard trip for the weekend, so I won't be able to put in much time on this project much until next weekend at the earliest. 
Looking forward to seeing your initial code though!

**Comment by n0v1c3** [comment]
Take a look at where I am at. You can close this issue once you see this and we can create proper ones as needed.
