### ISSUE TITLE
Config not being read

### ISSUE THREAD

**Issue by piotryordanov** [n0v1c3/vira#73]
I am running the `dev` branch of the plugin. 
I have created the files and populated them with the required credentials.

Yet, running `:ViraServers` fails. Any idea why?

![image](https://user-images.githubusercontent.com/48773775/122899885-e3f30400-d354-11eb-89b5-c5322c1d8303.png)

**Comment by piotryordanov** [comment]
Also, after I press enter on the error window, I get this 
![image](https://user-images.githubusercontent.com/48773775/122900069-0a18a400-d355-11eb-8cfb-a6b6d1be5a6a.png)

**Comment by piotryordanov** [comment]
Nevermind. I had a few python plugins that weren't installed. Works now!
Thx for the great project guys!

**Comment by n0v1c3** [comment]
Thank you. I am glad we could help with this issue!
