### ISSUE TITLE
ViraReport unreadable on "dark theme"

### ISSUE THREAD

**Issue by fetzig** [n0v1c3/vira#84]
Contrary to the gif in the README the `ViraReport` is unreadable when using a dark color theme. Most notably the `darkblue` of highlights for dates makes them unreadable.

![vira-demo-179 (dragged)](https://github.com/n0v1c3/vira/assets/105761/df70460b-ee46-4bb5-88ac-f17cc2a94449)

according to what I could find out this seems to be an issue with the highlights set in [syntax/vira_report.vim](https://github.com/n0v1c3/vira/blob/master/syntax/vira_report.vim#L176) and no setup issue on my side.

I have little to no experience with vim, thus I kindly ask you to clarify this. thx.

P.S.: I failed at overriding the highlight in my config files. Instead edited the vira_report.vim file. pointers on how to do this properly without monkey-patching are highly appreciated :)

**Comment by n0v1c3** [comment]
Hello @fetzig thanks for the feedback. I am assuming you are getting different results that we see in the demo `gif`. Would you want to send a simple copy of your `.vimrc` so I can try to reproduce the problem you are seeing? Try to make it the very basics to set your theme and plugin load `vira` then I will have a look at that.

Themes are always fun to work with to make sure it works with every other theme.

**Comment by fetzig** [comment]
hey, sorry for the late response.

using neovim with nvchad. much more than a single config file. sorry. that might be outside of your support scope ;) 

I'm certain I checked with vanilla neovim and had the same issue. This makes sense, since the original file sets darkblue as the font color. 

fixed it by adding an `after/syntax/vira_report.vim` which replaces all the darkblue from [the original](https://github.com/n0v1c3/vira/blob/master/syntax/vira_report.vim#L176) with green:

```vim
highlight viraCommentDate ctermfg=green guifg=green cterm=underline gui=underline
highlight viraDetailsDates ctermfg=green guifg=green
highlight viraDetailsTypeTask ctermfg=green guifg=green
highlight viraDetailsVersion ctermfg=green guifg=green
```

So for me this is good enough. Still, let me know if you like to get the config folder or any other info to investigate further.

**Comment by mikeboiko** [comment]
@fetzig, I recently switched to a new dark theme and I experienced the same issue as you.
I just changed all darkblue colors to green for the menu/report.
The fix is pushed to the dev branch.
